site_name: Notebook
site_url: https://note.ymzymz.me
site_description: Salvor's notbook
repo_name: silver-ymz/note
repo_url: https://github.com/silver-ymz/note/
site_author: silver

theme:
  name: "material"
  language: "zh"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: dark mode

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.js
  - js/katex.js

nav:
  - Home: index.md
  - Computer Science:
    - CS/index.md
    - 编程语言:
      - CS/PL/index.md
      - OCaml: CS/PL/OCaml.md
  - OoO (Out of Order):
    - 1.md
    - 2.md
    - 3.md
  